version: '2'
services:
    jeanne3-app:
        image: jeanne3
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jeanne3-mysql:3306/jeanne3?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=jeanne3-elasticsearch:9300
        ports:
            - 8080:8080
    jeanne3-mysql:
        extends:
            file: mysql.yml
            service: jeanne3-mysql
    jeanne3-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jeanne3-elasticsearch
